import type { AdapterAccountType } from "next-auth/adapters";
import {
  boolean,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/** Auth.js users table — `id` is a string UUID generated by the adapter. */
export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  image: text("image"),
  plan: text("plan")
    .notNull()
    .default("hobby")
    .$type<"hobby" | "pro">(),
  stripeCustomerId: text("stripeCustomerId"),
  stripeSubscriptionId: text("stripeSubscriptionId"),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [
    primaryKey({ columns: [t.provider, t.providerAccountId] }),
  ],
);

export const sessions = pgTable("sessions", {
  sessionToken: text("sessionToken").primaryKey(),
  userId: text("userId")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

export const authenticators = pgTable(
  "authenticators",
  {
    credentialID: text("credentialID").notNull().unique(),
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    providerAccountId: text("providerAccountId").notNull(),
    credentialPublicKey: text("credentialPublicKey").notNull(),
    counter: integer("counter").notNull(),
    credentialDeviceType: text("credentialDeviceType").notNull(),
    credentialBackedUp: boolean("credentialBackedUp").notNull(),
    transports: text("transports"),
  },
  (t) => [primaryKey({ columns: [t.userId, t.credentialID] })],
);

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    /** Per-project random 7-hex id stamped into Docker names, Traefik labels, and the public hostname. */
    hash: text("hash").notNull(),
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    /** Last successful tenant API touch (PostgREST) — used by the Flux reaper for idle stop. */
    lastAccessedAt: timestamp("last_accessed_at", { mode: "date" })
      .notNull()
      .defaultNow(),
    /** Last fleet monitor probe (PostgREST HTTP); null until the first check. */
    lastHeartbeatAt: timestamp("last_heartbeat_at", { mode: "date" }),
    /** Last probe outcome: `running` (2xx/3xx) or `error`. */
    healthStatus: text("health_status"),
    /** Execution engine: v1_dedicated (one container per project) or v2_shared (shared cluster). */
    mode: text("mode")
      .notNull()
      .default("v1_dedicated")
      .$type<"v1_dedicated" | "v2_shared">(),
  },
  (t) => [uniqueIndex("projects_user_slug_uniq").on(t.userId, t.slug)],
);

/** Sampled mesh probe results (fleet monitor; last N per project in UI). */
export const projectHeartbeatLog = pgTable(
  "project_heartbeat_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    recordedAt: timestamp("recorded_at", { mode: "date" })
      .notNull()
      .defaultNow(),
    healthStatus: text("health_status").notNull(),
  },
  (t) => [index("project_heartbeat_log_project_time_idx").on(t.projectId, t.recordedAt)],
);

/** Flux CLI / API keys — Bearer auth for `/api/cli/*` (raw secret never stored; only SHA-256 hash). */
export const apiKeys = pgTable(
  "flux_api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull().default("Default Key"),
    /** Constant segment for the current key family, e.g. `flx_live`. */
    keyPrefix: text("key_prefix").notNull(),
    /** SHA-256 hex digest of the full secret token (unique index for O(log n) lookup). */
    keyHash: text("key_hash").notNull().unique(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    lastUsedAt: timestamp("last_used_at", { mode: "date" }),
    revokedAt: timestamp("revoked_at", { mode: "date" }),
  },
  (t) => [index("flux_api_keys_user_id_idx").on(t.userId)],
);

/**
 * Custom-domain → project mapping used by the @flux/gateway for tenant resolution.
 * Every CRUD operation on this table must evict the Redis key `hostname:<normalizedHost>`
 * to prevent stale routing. See packages/gateway — cache invalidation contract.
 */
export const domains = pgTable(
  "domains",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** Normalized (lowercase, no port) hostname, e.g. `myapp.example.com`. */
    hostname: text("hostname").notNull().unique(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (t) => [index("domains_project_id_idx").on(t.projectId)],
);
