/**
 * Scoped MCP token capabilities — re-exported from @flux/core.
 */

export {
  MCP_CAPABILITIES,
  type McpCapability,
} from "@flux/core/mcp-capabilities";

export {
  MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER,
  MCP_CAPABILITY_PRESET_MIGRATION_PLANNER,
  MCP_CAPABILITY_PRESET_READ_ONLY_DATA_INSPECTOR,
  MCP_CAPABILITY_PRESET_CONTROLLED_MIGRATION_APPLIER,
  MCP_CAPABILITY_PRESET_DEFINITIONS,
  type McpCapabilityPresetDefinition,
  type McpCapabilityPresetId,
} from "@flux/core/mcp-capability-presets";

import {
  MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER,
  MCP_CAPABILITY_PRESET_MIGRATION_PLANNER,
  MCP_CAPABILITY_PRESET_READ_ONLY_DATA_INSPECTOR,
  MCP_CAPABILITY_PRESET_CONTROLLED_MIGRATION_APPLIER,
} from "@flux/core/mcp-capability-presets";

/** @deprecated Use MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER */
export const MCP_CAPABILITY_PRESET_SCHEMA_INSPECTOR =
  MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER;

export const MCP_CAPABILITY_PRESETS = {
  readOnlyObserver: MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER,
  schemaInspector: MCP_CAPABILITY_PRESET_READ_ONLY_OBSERVER,
  migrationPlanner: MCP_CAPABILITY_PRESET_MIGRATION_PLANNER,
  readOnlyDataInspector: MCP_CAPABILITY_PRESET_READ_ONLY_DATA_INSPECTOR,
  controlledMigrationApplier: MCP_CAPABILITY_PRESET_CONTROLLED_MIGRATION_APPLIER,
} as const;
